package cctv.cn.ipanda.model.db.db_dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cctv.cn.ipanda.model.db.db_dao.ChinaLiveTabAllListBeanDb;
import cctv.cn.ipanda.model.db.db_dao.ChinaLiveTabListBeanDb;
import cctv.cn.ipanda.model.db.db_dao.LoginEntityDb;

import cctv.cn.ipanda.model.db.db_dao.ChinaLiveTabAllListBeanDbDao;
import cctv.cn.ipanda.model.db.db_dao.ChinaLiveTabListBeanDbDao;
import cctv.cn.ipanda.model.db.db_dao.LoginEntityDbDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chinaLiveTabAllListBeanDbDaoConfig;
    private final DaoConfig chinaLiveTabListBeanDbDaoConfig;
    private final DaoConfig loginEntityDbDaoConfig;

    private final ChinaLiveTabAllListBeanDbDao chinaLiveTabAllListBeanDbDao;
    private final ChinaLiveTabListBeanDbDao chinaLiveTabListBeanDbDao;
    private final LoginEntityDbDao loginEntityDbDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chinaLiveTabAllListBeanDbDaoConfig = daoConfigMap.get(ChinaLiveTabAllListBeanDbDao.class).clone();
        chinaLiveTabAllListBeanDbDaoConfig.initIdentityScope(type);

        chinaLiveTabListBeanDbDaoConfig = daoConfigMap.get(ChinaLiveTabListBeanDbDao.class).clone();
        chinaLiveTabListBeanDbDaoConfig.initIdentityScope(type);

        loginEntityDbDaoConfig = daoConfigMap.get(LoginEntityDbDao.class).clone();
        loginEntityDbDaoConfig.initIdentityScope(type);

        chinaLiveTabAllListBeanDbDao = new ChinaLiveTabAllListBeanDbDao(chinaLiveTabAllListBeanDbDaoConfig, this);
        chinaLiveTabListBeanDbDao = new ChinaLiveTabListBeanDbDao(chinaLiveTabListBeanDbDaoConfig, this);
        loginEntityDbDao = new LoginEntityDbDao(loginEntityDbDaoConfig, this);

        registerDao(ChinaLiveTabAllListBeanDb.class, chinaLiveTabAllListBeanDbDao);
        registerDao(ChinaLiveTabListBeanDb.class, chinaLiveTabListBeanDbDao);
        registerDao(LoginEntityDb.class, loginEntityDbDao);
    }
    
    public void clear() {
        chinaLiveTabAllListBeanDbDaoConfig.clearIdentityScope();
        chinaLiveTabListBeanDbDaoConfig.clearIdentityScope();
        loginEntityDbDaoConfig.clearIdentityScope();
    }

    public ChinaLiveTabAllListBeanDbDao getChinaLiveTabAllListBeanDbDao() {
        return chinaLiveTabAllListBeanDbDao;
    }

    public ChinaLiveTabListBeanDbDao getChinaLiveTabListBeanDbDao() {
        return chinaLiveTabListBeanDbDao;
    }

    public LoginEntityDbDao getLoginEntityDbDao() {
        return loginEntityDbDao;
    }

}
