package cctv.cn.ipanda.model.db.db_dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cctv.cn.ipanda.model.db.db_dao.ChinaLiveTabListBeanDb;
import cctv.cn.ipanda.model.db.db_dao.ChinaLiveTabAllListBeanDb;

import cctv.cn.ipanda.model.db.db_dao.ChinaLiveTabListBeanDbDao;
import cctv.cn.ipanda.model.db.db_dao.ChinaLiveTabAllListBeanDbDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chinaLiveTabListBeanDbDaoConfig;
    private final DaoConfig chinaLiveTabAllListBeanDbDaoConfig;

    private final ChinaLiveTabListBeanDbDao chinaLiveTabListBeanDbDao;
    private final ChinaLiveTabAllListBeanDbDao chinaLiveTabAllListBeanDbDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chinaLiveTabListBeanDbDaoConfig = daoConfigMap.get(ChinaLiveTabListBeanDbDao.class).clone();
        chinaLiveTabListBeanDbDaoConfig.initIdentityScope(type);

        chinaLiveTabAllListBeanDbDaoConfig = daoConfigMap.get(ChinaLiveTabAllListBeanDbDao.class).clone();
        chinaLiveTabAllListBeanDbDaoConfig.initIdentityScope(type);

        chinaLiveTabListBeanDbDao = new ChinaLiveTabListBeanDbDao(chinaLiveTabListBeanDbDaoConfig, this);
        chinaLiveTabAllListBeanDbDao = new ChinaLiveTabAllListBeanDbDao(chinaLiveTabAllListBeanDbDaoConfig, this);

        registerDao(ChinaLiveTabListBeanDb.class, chinaLiveTabListBeanDbDao);
        registerDao(ChinaLiveTabAllListBeanDb.class, chinaLiveTabAllListBeanDbDao);
    }
    
    public void clear() {
        chinaLiveTabListBeanDbDaoConfig.clearIdentityScope();
        chinaLiveTabAllListBeanDbDaoConfig.clearIdentityScope();
    }

    public ChinaLiveTabListBeanDbDao getChinaLiveTabListBeanDbDao() {
        return chinaLiveTabListBeanDbDao;
    }

    public ChinaLiveTabAllListBeanDbDao getChinaLiveTabAllListBeanDbDao() {
        return chinaLiveTabAllListBeanDbDao;
    }

}
